FROM node:20-alpine AS builder
WORKDIR /app
COPY package.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY --from=builder /app/out ./
COPY --from=builder /app/package.json ./
EXPOSE 3000
CMD ["node", "server.js"]
